version: "3"

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: "plain"

tasks:
  lock: conan lock create .

  install:
    cmds:
      - |
        conan install . \
          --profile="profiles/clang.ini" \
          --output-folder="build" \
          --build=missing

  generate:
    cmds:
      - |
        cmake . --preset default \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

  build: time cmake --build --preset default

  run: ./build/packages/compiler/daoc

  test: ctest --test-dir build --preset conan-debug
