version: "3"

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: "plain"
  BUILD_OS: "ubuntu-22.04"
  BUILD_COMPILER: "clang"
  BUILD_TYPE: "debug"

tasks:
  clean: rm -rf build

  lock: conan lock create .

  install:
    cmds:
      - |
        conan install . \
          --profile="profiles/${BUILD_OS}.${BUILD_COMPILER}.${BUILD_TYPE}.ini" \
          --output-folder="build" \
          --build=missing

  generate:
    aliases: [gen]
    cmds:
      - |
        cmake . --preset default \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

  build: time cmake --build --preset default

  run: ./build/apps/daoc/daoc

  test: ctest --test-dir build --preset conan-debug --parallel 4 --output-on-failure --verbose
