version: "3"

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: "plain"
  BUILD_OS: "linux"
  BUILD_COMPILER: "clang"
  BUILD_TYPE: "Debug"

  # TODO (andrew): disambiguate host vs target (a.k.a. conan build) settings

tasks:
  lock:
    cmds:
      - |
        conan lock create . \
          --profile:host="profiles/${BUILD_OS}.${BUILD_COMPILER}.ini" \
          --profile:build="profiles/${BUILD_OS}.${BUILD_COMPILER}.ini"

  install:
    cmds:
      - |
        conan install . \
          --profile:host="profiles/${BUILD_OS}.${BUILD_COMPILER}.ini" \
          --profile:build="profiles/${BUILD_OS}.${BUILD_COMPILER}.ini" \
          --output-folder="build" \
          --build=missing \
          --settings=build_type=${BUILD_TYPE}

  generate:
    aliases: [gen]
    cmds:
      - cmake . --preset default

  clean: cmake --build --preset default --target clean

  build: time cmake --build --preset default

  run: ./build/apps/daoc/daoc

  test: ctest --test-dir build --preset default --output-on-failure --verbose
