[settings]
arch=x86_64
build_type=Debug
compiler=clang
compiler.cppstd=20
compiler.libcxx=libc++
compiler.version=14
os=Linux

[conf]
tools.build:compiler_executables={'c': 'clang', 'cpp': 'clang++'}
