version: "3.8"

services:
  workspace:
    build:
      context: .
      dockerfile: "Dockerfile"

    volumes:
      - type: "bind"
        source: ".."
        target: "/workspace/dao"
        consistency: "cached"
      - "/var/run/docker.sock:/var/run/docker.sock"

    command: "/bin/sh -c 'while sleep 1000; do :; done'"
